# Generated by Django 5.2 on 2025-05-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='more_details_for_the_dedicated_page',
            field=models.TextField(default=' ', max_length=1000),
        ),
    ]
